#!/usr/bin/env bash
# This is a Bash script that Creates the file /var/run/myscript.pid containing its PID

killer() {
    rm /var/run/myscript.pid
    exit 0
}

trap "echo 'I hate the kill command' && killer" SIGTERM
trap "echo 'Y U no love me?!'" SIGINT
trap "killer" SIGQUIT
echo '$$' > /var/run/myscript.pid
while true
do
  echo "To infinity and beyond"
  sleep 2
done
