#!/usr/bin/env bash
# This is a script that are detached from the terminal and running in the background are called daemons or processes, need to be managed.

killer() {
    kill "$(pgrep -f /manage_my_process)"
    rm -f /var/run/my_process.pid &
}

if [[ "$1" == "start" ]]
then
    ./manage_my_process &
    echo "$!" > /var/run/my_process.pid
    echo "manage_my_process started"
elif [[ "$1" == "stop" ]]
then
    killer; echo "manage_my_process stopped";
elif [[ "$1" == "restart" ]]
then
    killer; ./manage_my_process &
    echo "$!" > /var/run/my_process.pid
    echo "manage_my_process restarted"
else
    echo "Usage: manage_my_process {start|stop|restart}"
fi
